apiVersion: apps/v1
kind: Deployment

metadata:
  name: cartservice
  namespace: online-boutique
  labels:
    app: cartservice

spec:
  replicas: 2

  selector:
    matchLabels:
      app: cartservice

  template:
    metadata:
      labels:
        app: cartservice

    spec:
      containers:
      - name: server

        image: us-central1-docker.pkg.dev/google-samples/microservices-demo/cartservice:v0.10.2

        ports:
        - containerPort: 7070

        env:
        - name: REDIS_ADDR
          value: "redis:6379"

        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"

          limits:
            cpu: "300m"
            memory: "256Mi"

        readinessProbe:
          tcpSocket:
            port: 7070
          initialDelaySeconds: 5
          periodSeconds: 10

        livenessProbe:
          tcpSocket:
            port: 7070
          initialDelaySeconds: 20
          periodSeconds: 20