apiVersion: apps/v1
kind: Deployment

metadata:
  name: adservice
  namespace: online-boutique
  labels:
    app: adservice

spec:
  replicas: 2

  selector:
    matchLabels:
      app: adservice

  template:
    metadata:
      labels:
        app: adservice

    spec:
      containers:
      - name: server

        image: us-central1-docker.pkg.dev/google-samples/microservices-demo/adservice:v0.10.5

        ports:
        - containerPort: 9555

        env:
        - name: PORT
          value: "9555"

        resources:
          requests:
            cpu: "200m"
            memory: "180Mi"

          limits:
            cpu: "300m"
            memory: "300Mi"

        readinessProbe:
          grpc:
            port: 9555
          initialDelaySeconds: 20
          periodSeconds: 15

        livenessProbe:
          grpc:
            port: 9555
          initialDelaySeconds: 20
          periodSeconds: 15