apiVersion: v1
kind: Service

metadata:
  name: currencyservice
  namespace: online-boutique

spec:
  selector:
    app: currencyservice

  ports:
  - port: 7000
    targetPort: 7000

  type: ClusterIP