apiVersion: apps/v1
kind: Deployment

metadata:
  name: recommendationservice
  namespace: online-boutique
  labels:
    app: recommendationservice

spec:
  replicas: 2

  selector:
    matchLabels:
      app: recommendationservice

  template:
    metadata:
      labels:
        app: recommendationservice

    spec:
      containers:
      - name: server

        image: us-central1-docker.pkg.dev/google-samples/microservices-demo/recommendationservice:v0.10.5

        ports:
        - containerPort: 8080

        env:
        - name: PORT
          value: "8080"

        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: "productcatalogservice:3550"

        - name: DISABLE_PROFILER
          value: "1"

        resources:
          requests:
            cpu: "100m"
            memory: "220Mi"

          limits:
            cpu: "200m"
            memory: "450Mi"

        readinessProbe:
          grpc:
            port: 8080
          periodSeconds: 5

        livenessProbe:
          grpc:
            port: 8080
          periodSeconds: 5